### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ispanos** [ptinopedila/ptinopedila#8]
# TODOs

- [ ] Remove pre-installed flatpaks before installing new ones.

---

- [ ] Add octave
- [ ] Add dynare support, without all texlive packages
- [ ] Find way to build larger images
  - [ ] Add texlive-scheme-minimal
- [ ] `echo "Hidden=true" >> /usr/share/applications/nvim.desktop`
- [ ] `org.signal.Signal.desktop`
- [x] `rm /usr/etc/skel.d/.config/autostart/bluefin-firstboot.desktop`
- [x] `rm /usr/etc/yafti.yml`

## System-wide

- [x] Disable beep `echo 'blacklist pcspkr' | sudo tee /etc/modprobe.d/beep-blacklist.conf`
- [x] Add default system-wide flatpaks -- or manage all flatpaks via yafti.
- [x] Make sure system-wide flatpaks are installed with flathub repo.
- [ ] Enable powertop (yafti or on image)?
- [ ] Set up VFIO things
- [x] ~~Disable ssh password login~~
- [x] `v4l2loopback`
    HOME ONLY (bluefin does it) - How do I add `v4l2loopback` and maybe xpadneo from [akmods](https://github.com/ublue-os/akmods)
- [ ] **Virtualization**
  - [ ] Install all packages required to share clipboard and directories with vms.
  - [ ] Apply virtualization fix to 1st gen Ryzen cpus.
        sudo grubby --args="kvm.ignore_msrs=1" --update-kernel=ALL
        # ? rpm-ostree kargs --append=kvm.ignore_msrs=1
- [ ] Disable bluetooth on startup
      sudo sed -i 's/^#AutoEnable=true/AutoEnable=false/' /etc/bluetooth/main.conf

### R

- [ ] Add iucar/cran copr for r.yml
- [ ] add radian (pip)?
- [ ] Add custom backgrounds

### Bluefin edits

- [x] Remove bluefin's user flatpaks
- [x] Replace /etc/yafti.yml with yafti-home.yml
- [x] Rename the OS in `os-release`
  `sed -i '/^PRETTY_NAME/s/Silverblue/Bluefin/' /usr/lib/os-release`

### From secureblue

- [x] authselect.sh
- [x] disable cups
- [x] ~~disableuserns.sh ?~~
- [x] rpmostree1.rules
- [x] ~~firstboot~~
- [x] ~~just~~
- [x] ~~chromium~~
- [x] ~~modprob.d ?~~
- [x] networkmanager ?
- [x] security ?
- [ ] alter pwquality
- [x] sysctl.d
- [ ] upower.service.d
- [ ] change `YESCRYPT_COST_FACTOR 11` in /etc/login.defs ?
- [x] signing.sh sounds like the signed image wont work without it....
- [x] ~~disableubluesystemsetup.sh + blufin-scripts. -> `disableuserns-scripts.yml` only in the non userns images.~~
- [ ] why is `common-bling.yml` used with bluefin images?
- [x] what if common files are not common among all images
- [x] why is `- type: yafti` in the recipes?

## System or User ?

- ZSH things:
  - [x] Make sure zsh defaults will make sense to new users, then:
    - [ ] Change to zsh
  - [x] change zsh config dir (`ZDOTDIR=$HOME/.config/zsh`) in `/etc/zsh/zshenv` <https://wiki.archlinux.org/title/XDG_Base_Directory#Hardcoded>

      sudo usermod {current_user} --shell /usr/bin/zsh

    - [x] Add [fast-syntax-highlighting](https://github.com/zdharma-continuum/fast-syntax-highlighting) instead of `zsh-syntax-highlighting`.

  - ~~Install [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md) using git too?~~

- [ ] Locale: (not sure if this will be done here and/or with sudo) # TEST IN VM

      sudo localectl set-locale LC_ADDRESS=el_GR.UTF-8
      sudo localectl set-locale LC_NAME=el_GR.UTF-8
      sudo localectl set-locale LC_MONETARY=el_GR.UTF-8
      sudo localectl set-locale LC_PAPER=el_GR.UTF-8
      sudo localectl set-locale LC_IDENTIFICATION=en_GB.UTF-8
      sudo localectl set-locale LC_TELEPHONE=el_GR.UTF-8
      sudo localectl set-locale LC_MEASUREMENT=el_GR.UTF-8
      sudo localectl set-locale LC_TIME=en_GB.UTF-8
      sudo localectl set-locale LC_NUMERIC=en_US.UTF-8

## User

- [ ] Create a dotfiles plugin for yafti?

- [ ] In Dotfiles: (! PERSONAL only)

      /usr/bin/git --git-dir=/home/{current_user}/.cfg/
                   --work-tree=/home/{current_user} update-index
                   --assume-unchanged /home/{current_user}/.config/sway/config || true

- [ ] Move just file to `.config/justfile` ?

## Upstream things

- [x] Fix this:
  - `rm -f /usr/share/applications/fish.desktop`
  - `rm -f /usr/share/applications/htop.desktop`
  - `rm -f /usr/share/applications/nvtop.desktop`
  - `rm -fr /usr/share/applications/gnome-system-monitor.desktop`

- [x] Add firewall-config
